
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package controller;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-27T23:21:34.139+03:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "InfoProviderService",
                      portName = "InfoProviderPort",
                      targetNamespace = "http://controller/",
                      wsdlLocation = "http://localhost:8080/project_1/services/InfoProviderPort?wsdl",
                      endpointInterface = "controller.InfoProvider")
                      
public class InfoProviderPortImpl implements InfoProvider {

    private static final Logger LOG = Logger.getLogger(InfoProviderPortImpl.class.getName());

    /* (non-Javadoc)
     * @see controller.InfoProvider#getInfo(java.lang.String arg0)*
     */
    public java.lang.String getInfo(java.lang.String arg0) { 
        LOG.info("Executing operation getInfo");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1326572702";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
