package controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-27T23:21:34.139+03:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://controller/", name = "InfoProvider")
@XmlSeeAlso({ObjectFactory.class})
public interface InfoProvider {

    @WebMethod(operationName = "GetInfo")
    @RequestWrapper(localName = "GetInfo", targetNamespace = "http://controller/", className = "controller.GetInfo")
    @ResponseWrapper(localName = "GetInfoResponse", targetNamespace = "http://controller/", className = "controller.GetInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
