package controller;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-27T23:21:34.155+03:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "InfoProviderService", 
                  wsdlLocation = "http://localhost:8080/project_1/services/InfoProviderPort?wsdl",
                  targetNamespace = "http://controller/") 
public class InfoProviderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://controller/", "InfoProviderService");
    public final static QName InfoProviderPort = new QName("http://controller/", "InfoProviderPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/project_1/services/InfoProviderPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InfoProviderService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/project_1/services/InfoProviderPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InfoProviderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InfoProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfoProviderService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public InfoProviderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InfoProviderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InfoProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns InfoProvider
     */
    @WebEndpoint(name = "InfoProviderPort")
    public InfoProvider getInfoProviderPort() {
        return super.getPort(InfoProviderPort, InfoProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfoProvider
     */
    @WebEndpoint(name = "InfoProviderPort")
    public InfoProvider getInfoProviderPort(WebServiceFeature... features) {
        return super.getPort(InfoProviderPort, InfoProvider.class, features);
    }

}
