
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package controller;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-02T17:32:50.687+03:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "WS_LibraryService",
                      portName = "WS_LibraryPort",
                      targetNamespace = "http://controller/",
                      wsdlLocation = "http://localhost:8080/project_1/services/WS_LibraryPort?wsdl",
                      endpointInterface = "controller.WSLibrary")
                      
public class WS_LibraryPortImpl implements WSLibrary {

    private static final Logger LOG = Logger.getLogger(WS_LibraryPortImpl.class.getName());

    /* (non-Javadoc)
     * @see controller.WSLibrary#getBooks()*
     */
    public java.util.List<controller.Book> getBooks() { 
        LOG.info("Executing operation getBooks");
        try {
            java.util.List<controller.Book> _return = new java.util.ArrayList<controller.Book>();
            controller.Book _returnVal1 = new controller.Book();
            _returnVal1.setAuthor("Author404497833");
            _returnVal1.setId(300672973);
            _returnVal1.setName("Name656695141");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see controller.WSLibrary#updateBook(controller.Book arg0)*
     */
    public void updateBook(controller.Book arg0) { 
        LOG.info("Executing operation updateBook");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see controller.WSLibrary#addBook(controller.Book arg0)*
     */
    public void addBook(controller.Book arg0) { 
        LOG.info("Executing operation addBook");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see controller.WSLibrary#deleteBook(java.lang.String arg0)*
     */
    public void deleteBook(java.lang.String arg0) { 
        LOG.info("Executing operation deleteBook");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
