package controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-02T17:32:50.703+03:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://controller/", name = "WS_Library")
@XmlSeeAlso({ObjectFactory.class})
public interface WSLibrary {

    @WebMethod(operationName = "GetBooks", action = "urn:GetBooks")
    @RequestWrapper(localName = "GetBooks", targetNamespace = "http://controller/", className = "controller.GetBooks")
    @ResponseWrapper(localName = "GetBooksResponse", targetNamespace = "http://controller/", className = "controller.GetBooksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<controller.Book> getBooks();

    @WebMethod(operationName = "UpdateBook", action = "urn:UpdateBook")
    @RequestWrapper(localName = "UpdateBook", targetNamespace = "http://controller/", className = "controller.UpdateBook")
    @ResponseWrapper(localName = "UpdateBookResponse", targetNamespace = "http://controller/", className = "controller.UpdateBookResponse")
    public void updateBook(
        @WebParam(name = "arg0", targetNamespace = "")
        controller.Book arg0
    );

    @WebMethod(operationName = "AddBook", action = "urn:AddBook")
    @RequestWrapper(localName = "AddBook", targetNamespace = "http://controller/", className = "controller.AddBook")
    @ResponseWrapper(localName = "AddBookResponse", targetNamespace = "http://controller/", className = "controller.AddBookResponse")
    public void addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        controller.Book arg0
    );

    @WebMethod(operationName = "DeleteBook", action = "urn:DeleteBook")
    @RequestWrapper(localName = "DeleteBook", targetNamespace = "http://controller/", className = "controller.DeleteBook")
    @ResponseWrapper(localName = "DeleteBookResponse", targetNamespace = "http://controller/", className = "controller.DeleteBookResponse")
    public void deleteBook(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
